spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/eventstore
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest # Read from the beginning if no offset is found
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  datasource:
    url: jdbc:postgresql://localhost:5432/eventstore
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Change as needed for your environment
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect